### ISSUE TITLE
Can you share the model training process and “self_supervised. pth”？

### ISSUE THREAD

**Issue by AboutRT** [shamimtowhid/encrypted_network_traffic_classification_in_SDN#1]

**Comment by shamimtowhid** [comment]
Thank you for your comments. 

The trained model (self-supervised.pth) along with the dataset is added to the repository.

The model training process is described in detail in our paper. The paper is accepted in NetSoft 2022. Once the paper is published through the conference, the README page will be updated with the link to the paper.
